### ISSUE TITLE
if the field is a reference, can't define this field to a optional

### ISSUE THREAD

**Issue by fugang** [art049/odmantic#127]
# Bug
```
class A(Model):
    a: int = 1

class B(Model):
    b: Optional[A] = Reference()
```

### Current Behavior

it occurs a error 
```
TypeError: Unhandled field definition B: typing.Union[__main__.A, NoneType] = <odmantic.reference.ODMReferenceInfo object at 0x7fdb8e628798>
```

### Expected behavior

it should work

### Environment

- ODMantic version: 0.3.4
- MongoDB version: ...
- Pydantic infos (output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())`):
```
             pydantic version: 1.8.1
            pydantic compiled: True
                 install path: /usr/local/lib/python3.7/dist-packages/pydantic
               python version: 3.7.3 (default, Apr  3 2019, 19:16:38)  [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
                     platform: Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
     optional deps. installed: ['typing-extensions']
```

```
...
```

- Version of additional modules (if relevant):
  - ...

**Additional context**

_Add any other context about the problem here._

**Comment by AdrianJohnston** [comment]
I've got the same problem. Did you manage to figure out a work around?

**Comment by fugang** [comment]
> same

just don't define the reference field

**Comment by fugang** [comment]
> I've got the same problem. Did you manage to figure out a work around?

don't define as the reference field.

**Comment by AdrianJohnston** [comment]
> > I've got the same problem. Did you manage to figure out a work around?
> 
> don't define as the reference field.
Thanks for replying. 
Yea, that is what I ended up doing. 

Its unfortunate, as manually requesting all the data for the References is a bit tedious.
If it becomes more of an issue, I might have to track this bug down.

**Comment by h8h** [comment]
I have the same problem. Maybe you have a workaround.

Lets say I have two models defined:


```
from typing import Dict
from odmantic import Model

class Project(Model):
    data : Dict[str, str]

class Issue(Model):
    data : Dict[str, str]
    project : Project = Reference()

```

I want to use fastapi and have the following routes:


```
@router.get("/projects", name="api:projects")
async def get_projects(request: Request):
    return await request.app.state.db.find(Project)

@router.get("/projects/{id}", response_model=Project)
async def get_project_by_id(request: Request, id: ObjectId):
    project = await request.app.state.db.find_one(Project, Project.id == id)
    if project is None:
        raise HTTPException(404)
    return project 
```


So for Issue i want to use a slug path

`/projects/{projects_id}/issue`

```
@router.post("/projects/{slug}/issue", name="api:issues")
async def create_issue (slug: ObjectId, request: Request, issue: Issue):
    project = await request.app.state.db.find_one(Project, Project.id == slug)
    issue.project = project
    await request.app.state.db.save(issue)
    return issue
```

As you can see i create a reference for a new issue to an existing project.

But this fails:
```
{
  "detail": [
    {
      "loc": [
        "body",
        "project"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    }
  ]
}
```

That means that the project is required by FastAPI .

If I set the Project reference to optional it fails:
```
class Issue(Model):
    data : Dict[str, str]
    project : Optional[Project] = Reference(key_name="project")
```

```
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/odmantic/model.py", line 295, in __validate_cls_namespace__
    parse_obj_as(field_type, value)
  File "/usr/local/lib/python3.7/dist-packages/pydantic/tools.py", line 35, in parse_obj_as
    return model_type(__root__=obj).__root__
  File "/usr/local/lib/python3.7/dist-packages/pydantic/main.py", line 406, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[Union[api.models.projects.Project, NoneType]]
__root__
  value is not a valid dict (type=type_error.dict)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/_impl/asyncio.py", line 47, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/_impl/asyncio.py", line 54, in serve
    config.load()
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/config.py", line 306, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/backend/api/main.py", line 4, in <module>
    from api.routes.router import router as api_router
  File "/opt/backend/api/routes/router.py", line 2, in <module>
    from api.routes import projects, issues
  File "/opt/backend/api/routes/issues.py", line 5, in <module>
    from api.models.issues import Issue
  File "/opt/backend/api/models/issues.py", line 6, in <module>
    class Issue(Model):
  File "/usr/local/lib/python3.7/dist-packages/odmantic/model.py", line 386, in __new__
    mcs.__validate_cls_namespace__(name, namespace)
  File "/usr/local/lib/python3.7/dist-packages/odmantic/model.py", line 298, in __validate_cls_namespace__
    f"Unhandled field definition {name}: {repr(field_type)}"
TypeError: Unhandled field definition Issue: typing.Union[api.models.projects.Project, NoneType] = <odmantic.reference.ODMReferenceInfo object at 0x7f64a5306b88>
```

Thank you

**Comment by AdrianJohnston** [comment]
> I have the same problem. Maybe you have a workaround.

My issue was related but slightly different.

I ended up just swapping the Reference for an Optional[ObjectId]. 
Then I have to manually fetch the data for the reference for each parent class.
Which makes the code significantly more verbose (and slower) 

Sorry I cant be of more help.

**Comment by supermodo** [comment]
Same problem.

My workaround is to use 2 different models.
Something like this:
```python
class TreeModel(Model):
    '''Model to CREATE the tree'''
    height: float
    owner: Optional[ObjectId]

class TreeRead(Model):
    '''Model to READ the tree'''
    height: float
    owner: UserModel = Reference()
```
Hope it can help.
