### ISSUE TITLE
Crash when opening docs with fastapi + EmbeddedModel + ForwardRef

### ISSUE THREAD

**Issue by benyaming** [art049/odmantic#151]
# Bug

If odmantic model contains `EmbeddedModel`, it crashes when fastapi tries to build `openapi.json`

### Current Behavior

Here is minimal example:
```python3
from abc import ABC

from odmantic import Model, EmbeddedModel
from fastapi import FastAPI
import uvicorn


class MyModel(Model, ABC):
    a: int
    b: str
    c: 'MyEmbeddedModel'


class MyEmbeddedModel(EmbeddedModel, ABC):
    d: bool


app = FastAPI()


@app.get('/', response_model=MyModel)
async def test():
    ...


uvicorn.run(app)
```
Amd when I open localhost:8000/docs,
```python3
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\fastapi\applications.py", line 152, in openapi
    return JSONResponse(self.openapi())
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\fastapi\applications.py", line 137, in openapi
    servers=self.servers,
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\fastapi\openapi\utils.py", line 377, in get_openapi
    flat_models=flat_models, model_name_map=model_name_map
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\fastapi\utils.py", line 25, in get_model_definitions
    model, model_name_map=model_name_map, ref_prefix=REF_PREFIX
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\pydantic\schema.py", line 554, in model_process_schema
    known_models=known_models,
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\pydantic\schema.py", line 595, in model_type_schema
    known_models=known_models,
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\pydantic\schema.py", line 248, in field_schema
    known_models=known_models or set(),
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\pydantic\schema.py", line 502, in field_type_schema
    known_models=known_models,
  File "C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\lib\site-packages\pydantic\schema.py", line 839, in field_singleton_schema
    if issubclass(field_type, BaseModel):
  File "c:\users\benyamin\appdata\local\programs\python\python37-32\lib\abc.py", line 143, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
INFO:     127.0.0.1:57117 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error

```

### Expected behavior

Generate `openapi.json` as regular

### Workaround
Declare Embedded class before the main class, so `ForwardRef` will not be used.

### Environment

- ODMantic version: 0.3.5
- MongoDB version: 4.4.2
- Pydantic infos
```              pydantic version: 1.8.2
            pydantic compiled: False
                 install path: C:\Users\benyamin\.virtualenvs\bus-api-cGyu96QS\Lib\site-packages\pydantic
               python version: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 18 2019, 23:46:00) [MSC v.1916 32 bit (Intel)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by art049** [comment]
Yes, forwardref are not supported yet. If you wish to implement the feature, I'd be glad to accept the change :)
