### ISSUE TITLE
ValueError: [TypeError("'ObjectId' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]

### ISSUE THREAD

**Issue by tyteen4a03** [art049/odmantic#168]
Using odmantic 0.3.5 with this model:

```
class Report(Model):
    description: str

    class Config:
        collection = "reports"
```

When trying to do `engine.find(Report)`, I get this error:

```
Traceback (most recent call last):
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/hypercorn/asyncio/context.py", line 39, in _handle
    await invoke_asgi(app, scope, receive, send)
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/hypercorn/utils.py", line 239, in invoke_asgi
    await app(scope, receive, send)
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    response_data = await serialize_response(
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/fastapi/routing.py", line 131, in serialize_response
    return jsonable_encoder(
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/fastapi/encoders.py", line 58, in jsonable_encoder
    return jsonable_encoder(
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/fastapi/encoders.py", line 93, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/fastapi/encoders.py", line 107, in jsonable_encoder
    jsonable_encoder(
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/fastapi/encoders.py", line 93, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/Users/tyteen4a03/.pyenv/versions/project/lib/python3.9/site-packages/fastapi/encoders.py", line 144, in jsonable_encoder
    raise ValueError(errors)
```

**Comment by art049** [comment]
This stack trace seems to be related to FastAPI. Please provide more information if you think the problem is related to ODMantic.
