### ISSUE TITLE
Can't change a field in embedded model of a model returned by Model.copy(deep=True)

### ISSUE THREAD

**Issue by bartoszflis-silvair** [art049/odmantic#228]
# Bug

Given a model definition like this:

```
class SubM(EmbeddedModel):
    count: int

class M(Model):
    submodel: SubM

model = M(submodel=SubM(count=1))
model_copy = model.copy(deep=True)
```
When I call `model_copy.submodel.count = 2`
Then an `AttributeError: 'SubM' object has no attribute '__fields_modified__'` occurs

### Current Behavior

```
import asyncio
from odmantic import AIOEngine, EmbeddedModel, Model

class SubM(EmbeddedModel):
    count: int

class M(Model):
    submodel: SubM


async def main():
    engine = AIOEngine(database="test")
    model = M(submodel=SubM(count=1))
    await engine.save(model)

    model = await engine.find_one(M)
    model_copy = model.copy(deep=True)
    model_copy.submodel.count = 2

    assert model_copy != model


if __name__ == "__main__":
    loop = asyncio.new_event_loop()
    loop.run_until_complete(main())
```
Running the above code results in the following exception:
```
Traceback (most recent call last):
  File "", line 27, in <module>
    loop.run_until_complete(main())
  File "/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "", line 20, in main
    model_copy.submodel.count = 2
  File "/lib/python3.10/site-packages/odmantic/model.py", line 606, in __setattr__
    self.__fields_modified__.add(name)
AttributeError: 'SubM' object has no attribute '__fields_modified__'
```

### Expected behavior

I expect the above code to run without error.

### Environment

- ODMantic version: 0.5.0
- MongoDB version: 5.0.9
- Pydantic infos (output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`):

```
            pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, May  9 2022, 12:55:22) [GCC 9.3.0]
                     platform: Linux-5.4.0-73-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

**Additional context**

The problem can be fixed by adding the following two lines to the example above:
```
    submodel_copy = model.submodel.copy(deep=True)
    model_copy.submodel = submodel_copy
```

**Comment by art049** [comment]
Thanks for the bug report! Will be fixed in the next release.
