### ISSUE TITLE
Literal validation error

### ISSUE THREAD

**Issue by SebastienDorgan** [art049/odmantic#274]
# Bug
I have a Literal inside my model, when I try to create an instance I have a validation error that makes me think that odmantic considers literals as forward ref.

### My model

```python
from typing import Literal, Mapping
from odmantic import Model, Field, EmbeddedModel


class Port(EmbeddedModel):
    name: str
    json_schema: str

VariableTypeLiteral = Literal['bool', 'int', 'float' 'datetime', 'timedelta', 'str', 'list[bool]', 'list[int]', 'list[float]', 'list[datetime]', 'list[timedelta]', 'list[str]']


class Variable(EmbeddedModel):
    name: str
    description: str
    type: VariableTypeLiteral


class Service(Model):
    name: str
    version: str
    description: str
    image: str
    iconBase64: str | None
    variables: list[Variable] = Field(default_factory=list)
    inputs: list[Port] = Field(default_factory=list)
    outputs: list[Port] = Field(default_factory=list)

```
### The test that fails

```Python
from pathlib import Path
import shunter.model as model


def test_service():
    srv = model.Service(
        name='tetst', 
        version='3.0', 
        description='a test service', 
        image='hello-world',
        iconBase64=None,
        variables=[
            model.Variable(
                name='v', 
                description='',
                type='list[int]'
            )
        ]
    )
    Path('test.json').write_text(srv.json())

if __name__ == '__main__':
    test_service()

```
### The error I got
```
>python tests/shunter/test_model.py 
Traceback (most recent call last):
  File "/home/sdorgan/projects/shunter/shunter-catalog/tests/shunter/test_model.py", line 23, in <module>
    test_service()
  File "/home/sdorgan/projects/shunter/shunter-catalog/tests/shunter/test_model.py", line 13, in test_service
    model.Variable(
  File "/home/sdorgan/miniconda3/envs/shunter/lib/python3.10/site-packages/odmantic/model.py", line 524, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Variable
type
  unexpected value; permitted: ForwardRef('bool'), ForwardRef('int'), ForwardRef('floatdatetime'), ForwardRef('timedelta'), ForwardRef('str'), ForwardRef('list[bool]'), ForwardRef('list[int]'), ForwardRef('list[float]'), ForwardRef('list[datetime]'), ForwardRef('list[timedelta]'), ForwardRef('list[str]') (type=value_error.const; given=list[int]; permitted=(ForwardRef('bool'), ForwardRef('int'), ForwardRef('floatdatetime'), ForwardRef('timedelta'), ForwardRef('str'), ForwardRef('list[bool]'), ForwardRef('list[int]'), ForwardRef('list[float]'), ForwardRef('list[datetime]'), ForwardRef('list[timedelta]'), ForwardRef('list[str]')))

```
### Note
The same test but using pydantic Field and BaseModel instead of Model and EmbeddedModel works 
## Expected behavior
The file test.json is created with the following content

```json
{
    "name": "tetst",
    "version": "3.0",
    "description": "a test service",
    "image": "hello-world",
    "iconBase64": null,
    "variables": [
        {
            "name": "v",
            "description": "",
            "type": "list[int]"
        }
    ],
    "inputs": [],
    "outputs": [],
    "id": "634861a9bb27b5c4eb8a27c0"
}
```
## Environment
- ODMantic version: 0.9.0
- MongoDB version: 6.0.2"
- Pydantic infos:
```
pydantic version: 1.10.2
pydantic compiled: True
install path: /home/sdorgan/miniconda3/envs/shunter/lib/python3.10/site-packages/pydantic
python version: 3.10.6 (main, Oct  7 2022, 20:19:58) [GCC 11.2.0]
platform: Linux-5.15.0-50-generic-x86_64-with-glibc2.35
optional deps. installed: ['typing-extensions']
```

**Comment by adeelsohailahmed** [comment]
This is a serious issue, @art049. 

We are also facing the same error with ODMantic Version `0.9.1`. ODMantic Version `0.8.0` works fine. No idea what changed. All our libraries are up-to-date.

FWIW, in our case, we are using just simple strings inside the `Literal` (such as `Literal["github", "jira"]]`).

**Comment by art049** [comment]
Thanks for bumping the issue. I just found out this has been introduced by #240 since handling literal is closely related to GenericAlias handling.
Incoming fix ⛑️
