### ISSUE TITLE
Using deprecated `pydantic.datetime_parse:parse_datetime` in Pydantic

### ISSUE THREAD

**Issue by vffuunnyy** [art049/odmantic#368]
# Bug

Using deprecated `pydantic.datetime_parse:parse_datetime` in Pydantic.

### Current Behavior

If I install Pydantic version 2+, I get the error below

```Traceback
Traceback (most recent call last):
  File "E:\code\python\...\main.py", line 8, in <module>
    from odmantic import AIOEngine
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\...-py3.10\lib\site-packages\odmantic\__init__.py", line 1, in <module>
    from .bson import ObjectId
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\...-py3.10\lib\site-packages\odmantic\bson.py", line 11, in <module>
    from pydantic.datetime_parse import parse_datetime
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\...-py3.10\lib\site-packages\pydantic\_migration.py", line 295, in wrapper
    raise PydanticImportError(f'`{import_path}` has been removed in V2.')
pydantic.errors.PydanticImportError: `pydantic.datetime_parse:parse_datetime` has been removed in V2.
```

### Expected behavior

you know.

### Environment

- ODMantic version: `odmantic = "^0.9.2"`
- MongoDB version: xxx
- Pydantic infos (output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())`):

```
pydantic version: 2.3.0
pydantic-core version: 2.6.3
pydantic-core build: profile=release pgo=false
   install path: C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\...-py3.10\Lib\site-packages\pydantic
 python version: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
       platform: Windows-10-10.0.23545-SP0
optional deps. installed: ['typing-extensions']

**Comment by vffuunnyy** [comment]
duplicate

**Comment by vffuunnyy** [comment]
duplicate
