### ISSUE TITLE
field.bind_pydantic_field(cls.__fields__[name]) KeyError: '_id'

### ISSUE THREAD

**Issue by TobiaszG24** [art049/odmantic#49]
Python: 3.7
**code**

```
from fastapi import FastAPI
from motor.motor_asyncio import AsyncIOMotorClient
from odmantic import AIOEngine, Model

class User(Model):
    name: str


client = AsyncIOMotorClient("mongodb://haas-authservice-db:27017/")
engine = AIOEngine(motor_client=client, database="auth-service")

app = FastAPI()

motor_collection = engine.get_collection(User)
print(motor_collection)
```

**Error**
```

AsyncIOMotorCollection(Collection(Database(MongoClient(host=['haas-authservice-db:27017'], document_class=dict, tz_aware=False, connect=False, driver=DriverInfo(name='Motor', version='2.3.0', platform='asyncio')), 'auth-service'), 'user'))

Process SpawnProcess-37:

Traceback (most recent call last):

File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap

self.run()

File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run

self._target(*self._args, **self._kwargs)

File "/venv/lib/python3.7/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started

target(sockets=sockets)

File "/venv/lib/python3.7/site-packages/uvicorn/main.py", line 419, in run

loop.run_until_complete(self.serve(sockets=sockets))

File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete

return future.result()

File "/venv/lib/python3.7/site-packages/uvicorn/main.py", line 426, in serve

config.load()

File "/venv/lib/python3.7/site-packages/uvicorn/config.py", line 328, in load

self.loaded_app = import_from_string(self.app)

File "/venv/lib/python3.7/site-packages/uvicorn/importer.py", line 20, in import_from_string

module = importlib.import_module(module_str)

File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

File "<frozen importlib._bootstrap>", line 983, in _find_and_load

File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 677, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 728, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "/app/app.py", line 7, in <module>

from endpoints import router, conf

File "/app/endpoints.py", line 8, in <module>

from models import *

File "/app/models.py", line 34, in <module>

class User(Model):

File "/venv/lib/python3.7/site-packages/odmantic/model.py", line 424, in __new__

return super().__new__(mcs, name, bases, namespace, **kwargs)

File "/venv/lib/python3.7/site-packages/odmantic/model.py", line 363, in __new__

field.bind_pydantic_field(cls.__fields__[name])

KeyError: '_id'
```

**Comment by art049** [comment]
Hello, thanks for the bug report !
I think only this snippet is not enough to reproduce the error unfortunately.
Here is what i have when running it:
```
AsyncIOMotorCollection(Collection(Database(MongoClient(host=['haas-authservice-db:27017'], document_class=dict, tz_aware=False, connect=False, driver=DriverInfo(name='Motor', version='2.3.0', platform='asyncio')), 'auth-service'), 'user'))
INFO:     Started server process [20493]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```
Could you include more details about the package used?
- uvicorn version
- fastapi version
- odmantic version
- pydantic version

**Comment by TobiaszG24** [comment]
It was a syntax error:

```
class GroupMember(Model):
    member_id: str
    member_role: str
    
class Groups(Model):
    _id: ObjectId # <------------- HERE :D 
    name: str 
    members: List[GroupMember
```
