### ISSUE TITLE
Openapi crashes with models contains custom type fields

### ISSUE THREAD

**Issue by Olegt0rr** [art049/odmantic#76]
## Bug
datetime field works fine with pydantic
But when I use datetime field in odmantic models - `openapi.json` creation crashes :( 

## Traceback
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 143, in openapi
    return JSONResponse(self.openapi())
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 121, in openapi
    self.openapi_schema = get_openapi(
  File "/usr/local/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 348, in get_openapi
    definitions = get_model_definitions(
  File "/usr/local/lib/python3.8/site-packages/fastapi/utils.py", line 25, in get_model_definitions
    m_schema, m_definitions, m_nested_models = model_process_schema(
  File "pydantic/schema.py", line 525, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 566, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 222, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 476, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 821, in pydantic.schema.field_singleton_schema
ValueError: Value not declarable with JSON Schema, field: name='created' type=_datetime required=True

```

## How to reproduce
Just add datetime field to your tree example from odmantioc docs.
E.g.: `birth: datetime`
Then launch fastapi and open `/docs` or `/redoc`

```python
from typing import List
from datetime import datetime

from fastapi import FastAPI, HTTPException

from odmantic import AIOEngine, Model, ObjectId


class Tree(Model):
    name: str
    average_size: float
    discovery_year: int
    birth: datetime


app = FastAPI()

engine = AIOEngine()


@app.put("/trees/", response_model=Tree)
async def create_tree(tree: Tree):
    await engine.save(tree)
    return tree


@app.get("/trees/", response_model=List[Tree])
async def get_trees():
    trees = await engine.find(Tree)
    return trees


@app.get("/trees/count", response_model=int)
async def count_trees():
    count = await engine.count(Tree)
    return count


@app.get("/trees/{id}", response_model=Tree)
async def get_tree_by_id(id: ObjectId):
    tree = await engine.find_one(Tree, Tree.id == id)
    if tree is None:
        raise HTTPException(404)
    return tree
```

**Comment by Olegt0rr** [comment]
Found some info

Since you use custom type `_datetime` instead of `datetime`, you should properly set schema creation for it

> Custom field types can customise the schema generated for them using the `__modify_schema__` class method; 
> see [Custom Data Types](https://pydantic-docs.helpmanual.io/usage/schema/#modifying-schema-in-custom-fields) for more details.

**Comment by Olegt0rr** [comment]
Or you can can inherit `_datetime` from `datetime`.

With added inheritage problem disappears (checked).

Hope it not breaks something else :)

**Comment by AndreMPCosta** [comment]
> Or you can can inherit `_datetime` from `datetime`.
> 
> With added inheritance problem disappears (checked).
> 
> Hope it not breaks something else :)

Hey @Olegt0rr 
Can you point me how did you fix this issue?
I'm having the same problem, and I'm not sure what you mean by inheriting _datetime from datetime.

Thanks!
